FROM python:3.10.0-slim-buster
ENV APP_HOME=/app 
RUN mkdir $APP_HOME
RUN mkdir $APP_HOME/staticfiles
WORKDIR $APP_HOME 

LABEL maintainer='kevinrenkes@gmail.com'
LABEL youtube="https://www.youtube.com/channel/UCDWAOdlHrmESuwyle03GrLw"
LABEL description="Development image for Movie Review Project"

ENV PYTHONDONTWRITEBYTECODE 1

ENV PYTHONUNBUFFERED 1

RUN apt-get update \
&& apt-get install -y build_essential \
&& apt-get install -y libpq-dev \
&& apt-get install -y gettext \
&& apt-get install -y netcat gcc postgresql \
&& apt-get purge -y --auto-remove -o APY::AutoRemove::RecommendsImport=false \

